# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

use_frameworks!
target 'EkycIprIOS' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for EkycIproovIOS
  pod 'IprLiveness', :git => 'https://github.com/nhatnuoc/IprLivenessPod.git'
  pod 'QKMRZParser', '~> 2.0.0'
  pod 'SwiftyTesseract', '~> 3.1.3'
  pod 'iProov'
  pod 'QTSCardReader'
  pod 'SVProgressHUD'
#  pod 'IDCardReader', :git => 'https://github.com/nhatnuoc/IDCardReaderPod.git'
#  pod "ObjectMapper", '~> 4.2'
#  pod "KeychainSwift", '~> 19.0'
#  pod "CryptoSwift", '~> 1.8.2'
#  pod "SignManager", '~> 1.0.9'
#  pod "OpenSSL-Universal", '~> 1.1.1100'
  
  pod "FontAwesome+iOS", :git => 'https://github.com/trungnguyen1791/ios-fontawesome.git', :commit => '0e6bf65'

end
#pre_install do |installer|
#  installer.pod_targets.each do |pod|
#    if pod.name == 'iProov'
#      def pod.build_type;
#        Pod::BuildType.static_library
#      end
#    end
#  end
#end

post_install do |installer|
  installer.pods_project.targets.each do |target|
#    if target.name == 'IDCardReader' then
#      target.build_configurations.each do |config|
#        config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'No'
#      end
#    end
#    if target.name == 'LivenessUtility' then
#      target.build_configurations.each do |config|
#        config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'No'
#      end
#    end
  
  if target.name == 'JOSESwift' then
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    elsif
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
    
  end
  
end
